---
apiVersion: v1
kind: Namespace
metadata:
  name: wled-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wled-proxy
  namespace: wled-proxy
  labels:
    app: wled-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wled-proxy
  template:
    metadata:
      labels:
        app: wled-proxy
    spec:
      imagePullSecrets:
      - name: dockerhub
      containers:
      - name: wled-proxy
        image: antitux/wled-proxy:latest
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: wled-proxy
  namespace: wled-proxy
  labels:
    service: wled-proxy
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: wled-proxy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wled-proxy-ingress
  namespace: wled-proxy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: wled-proxy.home.antitux.net
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: wled-proxy
              port:
                number: 80
  tls:
  - hosts:
    - 'wled-proxy.home.antitux.net'
    secretName: myingress-cert